### ISSUE TITLE
Improve examples.

### ISSUE THREAD

**Issue by ay13** [rfox90/meteor-dragula#3]
In the demo, if I change the "number" field in Mongol the list doesn't re-order. Also, the order is not saved/persisted to the collection so on a refresh everything reverts to the original. If it was truly reactive then I could have it open in 2 windows and the actions would be mirrored.

**Comment by rfox90** [comment]
I think your troubles here are with the example and not the package.

The examples you give require you to listen to dragular events. This is easily dooable but is not implemented in the example.

In particular there's no sort order the templates re-render with their new data and that's reactivity that I was looking for. 

A mirrored list should be doable with no package changes. Although I could do something similar to tabular and take over the control of the dataset. This wouldn't allow for much customization.

Give me awhile and I'll make some better examples.

**Comment by topaztee** [comment]
Have you used this library in a project yet ? I;m wondering How to actually access the strings of the boxes ive dropped in the right container? so if i drop string "hello" into the right container. how would one also push it into an array of strings. 
https://stackoverflow.com/questions/34042660/trying-to-push-a-string-into-an-array-using-dragula-js-and-meteor

**Comment by rfox90** [comment]
There's some stuff here: https://github.com/jasontsukamoto/Kanban-Meteor

That looks to be using it successfully. I'll look at the events and see if we can re-cast them out or something.
