### ISSUE TITLE
cant get dragging to work?

### ISSUE THREAD

**Issue by topaztee** [rfox90/meteor-dragula#5]

**Comment by rfox90** [comment]
Can you provide some code?

Does my example work?

**Comment by topaztee** [comment]
are we supposed to add the dist file into our project?

maybe the package.js file should include "  api.export('dragula');?

Pretty much, the dist file isnt loading

**Comment by topaztee** [comment]
Package.onUse(function (api) {
    api.add_files(['dragula/dist/dragula.css','dragula/dist/dragula.js'], ['client']);
});

this files arent loading.
even though i added ahref:dragula into the packages list

**Comment by rfox90** [comment]
Does the example app not work?

**Comment by topaztee** [comment]
It does work. But following the instructions on my own app has the dist file not loading.

**Comment by rfox90** [comment]
So in your own app if you load it up in a browser and do window.dragula in the console it is undefined?

**Comment by topaztee** [comment]
what it looks like: https://www.dropbox.com/s/prhkc7nfa1xemsv/Screenshot%202015-12-01%2000.14.55.png?dl=0

window.console  outputs:
dragula(initialContainers, options) {
  var len = arguments.length;
  if (len === 1 && Array.isArray(initialContainers) === false) {
    options = initialContainers;
    initialContainers = […

and an error Template.dragList.onRendered is not a function

**Comment by rfox90** [comment]
Dragula is defined and usable then. Everything has loaded correctly. 

If it wasn't in scope you'd see undefined. 

Provide you initialization code please.

https://github.com/rfox90/meteor-dragula/blob/master/example/testbed.js shows an example init. Its from the demo app.

Oh, I just saw your last line `Template.dragList.onRendered is not a function` means that you don't have a template called dragList.

You need to run onRendered on your actual template and not a template that isn't in play.

**Comment by topaztee** [comment]
will just try again tomorrow morning.

**Comment by rfox90** [comment]
Alright, your onRendered call should refer to your own template.

```
<template name="template1"></template>
Template.template1.onRendered();
```

```
<template name="productList"></template>
Template.productList.onRendered();
```

etc.

**Comment by topaztee** [comment]
I Finally found out what the problem was.. I was running an older version of meteor, a simple "meteor update" fixed it.

**Comment by rfox90** [comment]
Awesome, good luck!

**Comment by topaztee** [comment]
Is it possible to have more than 2 containers?

**Comment by rfox90** [comment]
https://github.com/bevacqua/dragula contains the documentation, containers is an array. Knock yourself out with as many containers as you want.
