### ISSUE TITLE
Consider Mirroring Version

### ISSUE THREAD

**Issue by jlukic** [rfox90/meteor-dragula#6]
It's difficult to tell what source version has changed when atmosphere version uses different semver #.

**Comment by rfox90** [comment]
Agreed.

Which also reminds me, If you notice that dragular has changed version poke me. I need to know. I'll get this sorted at some point today and update the readme to suggest people poke me about it.

**Comment by jlukic** [comment]
I'm currently running into issues with the package where I'm seeing the dragula source code in my project as identical to `3.5.1` even though it appears the submodule references `3.5.4` in your tagged release.

I've confirmed this is the case by installing `ahref:dragula` then checking `dragula.js` against the last few tagged releases using a diff. It appears to be an exact match with `3.5.1`

Any idea why this might be occurring?

**Comment by rfox90** [comment]
Apologies for the delay here.

I've been keeping up with Meteor 1.3 development which should make packages like this redundant. However as discussed I'll publish a new version soon that mirrors dragular's version. 

I'll double check the file contents too!

**Comment by rfox90** [comment]
> There's a caveat to dragula. You shouldn't include it in the `<head>` of your web applications. It's bad >practice to place scripts in the `<head>`, and as such dragula makes no effort to support this use case.
> 
> Place dragula in the `<body>`, instead.

Yeah, gonna require some tinkering.

**Comment by rfox90** [comment]
I've published 3.5.4

The module basically got re-written for this to use the NPM version and cosmos:browserify.
