### ISSUE TITLE
dragula is not defined

### ISSUE THREAD

**Issue by Kostanos** [rfox90/meteor-dragula#8]
Any idea why I got some times this error:

```
Exception from Tracker afterFlush function: debug.js:41
ReferenceError: dragula is not defined
```

Interesting that some time it works.
This is how I use it:

```
Template.mealsListMenuTab.onRendered(function(){
  var template = this;

  // --------------------
  // Drug & Drop Sections
  var sectionOptions = {
    moves: function (el, source, handle, sibling) {
      return $(handle).hasClass('section-move');
    },
  };
  this.sectionsDrake = dragula([document.getElementById('sectionTabs')], sectionOptions);
  ...
});
```

**Comment by Kostanos** [comment]
It seems dragula is not ready, even if Meteor already rendered the page, I'm not sure how it happens, but maybe there is a way to check if dragula is ready?

**Comment by Kostanos** [comment]
If you got the same issue, my workaround:

```
  var dragulaWatcher = null;
  dragulaWatcher = setInterval(function(){
    if (typeof dragula != 'function') return;

    clearInterval(dragulaWatcher);
    // Dragula initializing code here
  }, 500);

```

**Comment by rfox90** [comment]
Please don't do that. 

I see 1.3 is out. I'm deprecating this entire package

http://guide.meteor.com/using-packages.html#client-npm

Should give you native dragula support without this.
